import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import CpHeader from './commonComponent/cpHeader/cpHeader'
import CpLoader from './commonComponent/cpLoader/cpLoader'

const roboto = Roboto({ subsets: ['latin'],
weight:'400',
display:'swap'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <CpHeader/>
      <body className={roboto.className}>{children}
      </body>
    </html>
  )
}
